import Link from "next/link";
import Image from "next/image";
import Star from "../../../public/images/star.svg";
import IntegrationsImg01 from "../../../public/images/integrations-01.svg";
import IntegrationsImg02 from "../../../public/images/integrations-02.svg";
import IntegrationsImg03 from "../../../public/images/integrations-03.svg";
import IntegrationsImg04 from "../../../public/images/integrations-04.svg";
import IntegrationsImg05 from "../../../public/images/integrations-05.svg";
import IntegrationsImg06 from "../../../public/images/integrations-06.svg";
import IntegrationsImg07 from "../../../public/images/integrations-07.svg";
import IntegrationsImg08 from "../../../public/images/integrations-08.svg";
import IntegrationsImg09 from "../../../public/images/integrations-09.svg";
import IntegrationsImg10 from "../../../public/images/integrations-10.svg";
import IntegrationsImg11 from "../../../public/images/integrations-11.svg";
import IntegrationsImg12 from "../../../public/images/integrations-12.svg";
import IntegrationsImg13 from "../../../public/images/integrations-13.svg";
import IntegrationsImg14 from "../../../public/images/integrations-14.svg";
import IntegrationsImg15 from "../../../public/images/integrations-15.svg";
import IntegrationsImg16 from "../../../public/images/integrations-16.svg";
import IntegrationsImg17 from "../../../public/images/integrations-17.svg";
import IntegrationsImg18 from "../../../public/images/integrations-18.svg";
import IntegrationsImg19 from "../../../public/images/integrations-19.svg";
import IntegrationsImg20 from "../../../public/images/integrations-20.svg";
import IntegrationsImg21 from "../../../public/images/integrations-21.svg";
import IntegrationsImg22 from "../../../public/images/integrations-22.svg";
import IntegrationsImg23 from "../../../public/images/integrations-23.svg";
import IntegrationsImg24 from "../../../public/images/integrations-24.svg";

export const items = [
  {
    img: IntegrationsImg06,
    name: "stAPPL",
    description: "Synthetic represenation of your favorite real-world asset.",
    link: "/integrations/single-post",
    featured: true,
    category: "Stocks",
    price: "$314.87",
    volume: "$28895.3",
    change24h: "+9.99%",
  },
  {
    img: IntegrationsImg07,
    name: "Amazon.com",
    description:
      "Amazon.com, Inc. is an online retailer in North America and internationally. ",
    link: "/integrations/single-post",
    featured: false,
    category: "Stocks",
    price: "$387.39",
    volume: "$31077.07",
    change24h: "+7.78%",
  },
  {
    img: IntegrationsImg04,
    name: "Jira",
    description: "Synthetic represenation of your favorite real-world asset.",
    link: "/integrations/single-post",
    featured: true,
    category: "Stocks",
    price: "$216.23",
    volume: "$34992.94",
    change24h: "+2.91%",
  },
  {
    img: IntegrationsImg08,
    name: "GitHub",
    description: "Synthetic represenation of your favorite real-world asset.",
    link: "/integrations/single-post",
    featured: true,
    category: "Stocks",
    price: "$490.1",
    volume: "$47548.15",
    change24h: "+6.63%",
  },
  {
    img: IntegrationsImg05,
    name: "GitLab",
    description: "Synthetic represenation of your favorite real-world asset.",
    link: "/integrations/single-post",
    featured: true,
    category: "Stocks",
    price: "$332.04",
    volume: "$43831.68",
    change24h: "-0.49%",
  },
  {
    img: IntegrationsImg01,
    name: "Retool",
    description: "Synthetic represenation of your favorite real-world asset.",
    link: "/integrations/single-post",
    featured: true,
    category: "Stocks",
    price: "$280.01",
    volume: "$20439.2",
    change24h: "-9.12%",
  },
  {
    img: IntegrationsImg02,
    name: "Zapier",
    description: "Synthetic represenation of your favorite real-world asset.",
    link: "/integrations/single-post",
    featured: true,
    category: "Derivatives",
    price: "$261.7",
    volume: "$14452.08",
    change24h: "+6.08%",
  },
  {
    img: IntegrationsImg03,
    name: "Airtable",
    description: "Synthetic represenation of your favorite real-world asset.",
    link: "/integrations/single-post",
    featured: true,
    category: "Derivatives",
    price: "$418.89",
    volume: "$31947.85",
    change24h: "+3.37%",
  },
  {
    img: IntegrationsImg09,
    name: "Framer",
    description: "Synthetic represenation of your favorite real-world asset.",
    link: "/integrations/single-post",
    featured: true,
    category: "Derivatives",
    price: "$284.41",
    volume: "$37212.96",
    change24h: "+2.94%",
  },
  {
    img: IntegrationsImg10,
    name: "Jotform",
    description: "Synthetic represenation of your favorite real-world asset.",
    link: "/integrations/single-post",
    featured: false,
    category: "Derivatives",
    price: "$467.39",
    volume: "$20697.04",
    change24h: "-4.7%",
  },
  {
    img: IntegrationsImg11,
    name: "Webflow",
    description: "Synthetic represenation of your favorite real-world asset.",
    link: "/integrations/single-post",
    featured: true,
    category: "Derivatives",
    price: "$245.05",
    volume: "$22586.44",
    change24h: "+8.33%",
  },
  {
    img: IntegrationsImg12,
    name: "Coda",
    description: "Synthetic represenation of your favorite real-world asset.",
    link: "/integrations/single-post",
    featured: false,
    category: "Derivatives",
    price: "$301.75",
    volume: "$12662.13",
    change24h: "+6.37%",
  },
  {
    img: IntegrationsImg13,
    name: "Asana",
    description: "Synthetic represenation of your favorite real-world asset.",
    link: "/integrations/single-post",
    featured: true,
    category: "Commodities",
    price: "$382.33",
    volume: "$34951.73",
    change24h: "-2.49%",
  },
  {
    img: IntegrationsImg14,
    name: "Myngo",
    description: "Synthetic represenation of your favorite real-world asset.",
    link: "/integrations/single-post",
    featured: true,
    category: "Commodities",
    price: "$458.62",
    volume: "$14848.69",
    change24h: "+1.12%",
  },
  {
    img: IntegrationsImg15,
    name: "Bonsai",
    description: "Synthetic represenation of your favorite real-world asset.",
    link: "/integrations/single-post",
    featured: true,
    category: "Commodities",
    price: "$325.73",
    volume: "$40634.87",
    change24h: "-6.3%",
  },
  {
    img: IntegrationsImg16,
    name: "Decipad",
    description: "Synthetic represenation of your favorite real-world asset.",
    link: "/integrations/single-post",
    featured: true,
    category: "Commodities",
    price: "$337.39",
    volume: "$42322.09",
    change24h: "+5.99%",
  },
  {
    img: IntegrationsImg17,
    name: "Miro",
    description: "Synthetic represenation of your favorite real-world asset.",
    link: "/integrations/single-post",
    featured: true,
    category: "Commodities",
    price: "$496.67",
    volume: "$36190.65",
    change24h: "+9.38%",
  },
  {
    img: IntegrationsImg18,
    name: "Popform",
    description: "Synthetic represenation of your favorite real-world asset.",
    link: "/integrations/single-post",
    featured: true,
    category: "Commodities",
    price: "$194.9",
    volume: "$41293.39",
    change24h: "+7.5%",
  },
  {
    img: IntegrationsImg19,
    name: "Linear",
    description: "Synthetic represenation of your favorite real-world asset.",
    link: "/integrations/single-post",
    featured: true,
    category: "Crypto",
    price: "$445.11",
    volume: "$27178.4",
    change24h: "+2.45%",
  },
  {
    img: IntegrationsImg20,
    name: "Microsoft",
    description: "Synthetic represenation of your favorite real-world asset.",
    link: "/integrations/single-post",
    featured: true,
    category: "Crypto",
    price: "$297.4",
    volume: "$46276.18",
    change24h: "-6.21%",
  },
  {
    img: IntegrationsImg21,
    name: "Google Drive",
    description: "Synthetic represenation of your favorite real-world asset.",
    link: "/integrations/single-post",
    featured: true,
    category: "Crypto",
    price: "$493.09",
    volume: "$42774.62",
    change24h: "-7.94%",
  },
  {
    img: IntegrationsImg22,
    name: "InVision",
    description: "Synthetic represenation of your favorite real-world asset.",
    link: "/integrations/single-post",
    featured: true,
    category: "Crypto",
    price: "$316.55",
    volume: "$26057.91",
    change24h: "-1.95%",
  },
  {
    img: IntegrationsImg23,
    name: "WeTransfer",
    description: "Synthetic represenation of your favorite real-world asset.",
    link: "/integrations/single-post",
    featured: false,
    category: "Crypto",
    price: "$255.91",
    volume: "$12700.05",
    change24h: "+8.37%",
  },
  {
    img: IntegrationsImg24,
    name: "Hotjar",
    description: "Synthetic represenation of your favorite real-world asset.",
    link: "/integrations/single-post",
    featured: true,
    category: "Crypto",
    price: "$135.24",
    volume: "$18658.83",
    change24h: "+7.8%",
  },
  {
    img: IntegrationsImg24,
    name: "Tech Titans",
    description: "A collection of large-cap technology stocks.",
    link: "/integrations/single-post",
    featured: true,
    category: "etfs",
    price: "$135.24",
    volume: "$18658.83",
    change24h: "+7.8%",
  },
  {
    img: IntegrationsImg24,
    name: "Green Energy Leaders",
    description: "Top renewable energy and clean tech companies",
    link: "/integrations/single-post",
    featured: true,
    category: "etfs",
    price: "$135.24",
    volume: "$18658.83",
    change24h: "+7.8%",
  },
  {
    img: IntegrationsImg24,
    name: "Biotech Innovators",
    description: "Collection comprising cutting-edge biotech firms",
    link: "/integrations/single-post",
    featured: true,
    category: "etfs",
    price: "$135.24",
    volume: "$18658.83",
    change24h: "+7.8%",
  },
  {
    img: IntegrationsImg24,
    name: "Biotech Innovators",
    description: "Collection comprising cutting-edge biotech firms",
    link: "/integrations/single-post",
    featured: true,
    category: "etfs",
    price: "$135.24",
    volume: "$18658.83",
    change24h: "+7.8%",
  },
];
